# Generated by Django 3.0.4 on 2020-04-06 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=32)),
                ('vorgetpass', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Выберите способ доставки')),
            ],
        ),
        migrations.CreateModel(
            name='Methodpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('tel', models.IntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=32)),
                ('confirmpass', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('tel', models.IntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.CreateModel(
            name='Helmets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.PositiveIntegerField()),
                ('stock', models.CharField(max_length=16)),
                ('guarantee', models.CharField(max_length=16)),
                ('sale', models.TextField(blank=True)),
                ('equipment', models.TextField(blank=True)),
                ('characteristics', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.PositiveIntegerField()),
                ('num', models.PositiveIntegerField()),
                ('sum', models.PositiveIntegerField()),
                ('deliveryprice', models.PositiveIntegerField()),
                ('totalpurchse', models.PositiveIntegerField()),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prodapp.Delivery')),
                ('methodpay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prodapp.Methodpay')),
                ('userinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prodapp.Userinfo')),
            ],
        ),
    ]
