# Generated by Django 3.0.4 on 2020-04-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0002_auto_20200406_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authorisation',
        ),
        migrations.RemoveField(
            model_name='box',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='box',
            name='methodpay',
        ),
        migrations.RemoveField(
            model_name='box',
            name='userinfo',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Box',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Methodpay',
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
