# Generated by Django 3.0.4 on 2020-04-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0003_auto_20200407_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helmets',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='helmets',
            name='equipment',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='helmets',
            name='guarantee',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='helmets',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='helmets',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='helmets',
            name='price',
            field=models.CharField(max_length=16),
        ),
    ]
