# Generated by Django 3.0.4 on 2020-04-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0004_auto_20200407_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='helmets',
            name='text',
            field=models.CharField(default='Новое поколение игровых гарнитур', max_length=84),
        ),
    ]
