# Generated by Django 3.0.4 on 2020-04-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0005_helmets_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helmets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='helmets'),
        ),
    ]
