# Generated by Django 3.0.4 on 2020-04-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0006_auto_20200410_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='carusel')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='carusel')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='carusel')),
            ],
        ),
    ]
