# Generated by Django 3.0.4 on 2020-04-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Выберите способ доставки')),
            ],
        ),
        migrations.CreateModel(
            name='Methodpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('tel', models.IntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.PositiveIntegerField()),
                ('num', models.PositiveIntegerField()),
                ('sum', models.PositiveIntegerField()),
                ('deliveryprice', models.PositiveIntegerField()),
                ('totalpurchse', models.PositiveIntegerField()),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boxapp.Delivery')),
                ('methodpay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boxapp.Methodpay')),
                ('userinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boxapp.Userinfo')),
            ],
        ),
    ]
