# Generated by Django 3.0.4 on 2020-04-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxapp', '0002_auto_20200422_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='comment',
            field=models.CharField(max_length=250, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxapp.Delivery', verbose_name='Способ доставки'),
        ),
    ]
